name: Send quote of the day

on:
  push:
    paths:
      - .github/workflows/qotd.yaml
      - send_potd.py
      - send_qotd.py
      - bot_sender.py
  workflow_dispatch:
  schedule:
    - cron: 13 08 * * *

env:
  TG_USER: ${{secrets.TG_USER}}
  TG_PASS: ${{secrets.TG_PASS}}

jobs:
  send-qotd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: python send_qotd.py

  send-potd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Send picture of the day
        run: python send_potd.py