name: Send quote of the day

on:
  schedule:
    - cron: 13 08 * * *

env:
  TG_USER: ${{secrets.TG_USER}}
  TG_PASS: ${{secrets.TG_PASS}}

jobs:
  send-qotd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python send_qotd.py